### PR TITLE
fixes url, adds two libs

### PR DESCRIPTION
**Pull request by jonschlinkert**
Fixes the URL for `inflection`, and adds `pluralize` and `is-plural`

### CODE REVIEW

**Comment by jonschlinkert** [comment]
ping

**Comment by zeke** [comment]
Hey, @jonschlinkert. Sorry I missed this. I know it's been many 🌑 🌔 🌓 🌖 🌕 but if you want to rebase I'll happily merge and cut a new release.

**Comment by jonschlinkert** [comment]
hey @zeke, no worries! I saw this the other day on my phone and forgot to reply. 

> rebase I'll happily merge and cut a new release.

I'll do this as soon as I have a chance, thanks!

**Comment by zeke** [comment]
Sounds good!

**Pull request closed without merging**
